### ISSUE TITLE
ПОЛНАЯ ПОЕБЕНЬ

### ISSUE THREAD

**Issue by azazalkaproxl** [medadon41/bsuir-frontend#1]
ПЕРЕДЕЛЫВАЙ

**Comment by azazalkaproxl** [comment]
🎁

**Comment by medadon41** [comment]
сам переделывай тварь

**Comment by azazalkaproxl** [comment]
Have you heard of opera gx? its the very first browser for gamers opera gx includes a feature called gx control which lets you do some #controlling on your cpu Ram or network usage. You already know chrome eats up ram so i mainly use fire fox but as you can see here the feature that made me imediately switch to opera gx was the force dark mode feature once i saw how blinding google docs was in firefox i knew i would be going back. Personally i only use soundcloud for music so i couldnt make usage of the built in player to spotify apple music and youtube music but when i open souncloud and listen to something it just sounds better on opera the side bar is also useful for pinning such as twitch and twitter makes it super easy to check notifications of my tweets and streams how you really know this is a gaming browser is from the built in rgb lighting that is fully customizable. Im honestly really liking opera gx it really feels like a new app rather than just a web browser and its even got its own background music which is turned off by default. Because gaming. If you re thinking of downloading opera gx lemme know in the comments im always looking
